version: '3.9'

services:
  music-web-store-app:
      build: ./music-web-store
      container_name: music-web-store-app
      environment:
        - DJANGO_SETTINGS_MODULE=music-web-store.settings
      entrypoint: ["/bin/sh", "-c"]
      command:
        - |
          python manage.py makemigrations
          python manage.py migrate
          python manage.py runserver 0.0.0.0:8000
      ports:
        - "8005:8000"
      depends_on:
        music-web-store-db:
          condition: service_healthy


  music-web-store-db:
    image: postgres:14
    container_name: music-web-store-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 30s
      retries: 6
    restart: always