# Generated by Django 4.0 on 2021-12-08 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.websiteuser'),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory_id',
            field=models.ManyToManyField(to='main.SubCategory'),
        ),
    ]
