# Generated by Django 4.0 on 2021-12-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subcategory_id',
            field=models.ManyToManyField(null=True, to='main.SubCategory'),
        ),
    ]
