# Generated by Django 4.0 on 2021-12-08 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category_id',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category_id',
            field=models.ManyToManyField(through='main.CategorySubCategory', to='main.Category'),
        ),
        migrations.AddField(
            model_name='categorysubcategory',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory'),
        ),
    ]
