# Generated by Django 4.0 on 2021-12-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_type',
            new_name='shipping_type',
        ),
    ]
