# Generated by Django 4.0 on 2021-12-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_delivery_type_order_shipping_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime_ordered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
