# Generated by Django 4.0 on 2021-12-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_order_datetime_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_type',
            field=models.TextField(choices=[('1', 'Pickup in person'), ('2', 'Home shipping')], default='1'),
        ),
    ]
