# Generated by Django 4.0 on 2021-12-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_amount_payed_order_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Credit card'), (3, 'Bank transfer'), (4, 'Wallet')], null=True),
        ),
    ]
