# Generated by Django 4.0 on 2021-12-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_shoppingcart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_type',
            field=models.IntegerField(choices=[(1, 'Pickup in person'), (2, 'Home shipping')], default=1),
        ),
    ]
