# Generated by Django 4.0 on 2021-12-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_order_shipping_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.TextField(null=True),
        ),
    ]
