# Generated by Django 4.0 on 2021-12-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteuser',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='websiteuser',
            name='email',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='websiteuser',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
