# Generated by Django 4.0.1 on 2022-02-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_websiteuser_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteuser',
            name='wallet',
            field=models.FloatField(default=0, null=True),
        ),
    ]
