# Generated by Django 4.0 on 2021-12-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteuser',
            name='wallet',
            field=models.IntegerField(null=True),
        ),
    ]
