# Generated by Django 4.0 on 2021-12-09 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_order_address_order_phone_number'),
        ('products', '0004_alter_product_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory_id',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory_id',
            field=models.ManyToManyField(through='products.SubCategoryProduct', to='main.SubCategory'),
        ),
        migrations.AddField(
            model_name='subcategoryproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='subcategoryproduct',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory'),
        ),
    ]
