# Generated by Django 4.0 on 2021-12-09 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_description'),
        ('users', '0001_initial'),
        ('main', '0004_categorysubcategory_remove_subcategory_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('datetime_ordered', models.DateTimeField()),
                ('delivery_type', models.TextField(choices=[('1', 'Pickup in person'), ('2', 'Home shipping')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.websiteuser')),
            ],
        ),
    ]
