# Generated by Django 4.0 on 2021-12-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.TextField(choices=[('1', 'Cash'), ('2', 'Credit card'), ('3', 'Bank transfer')], null=True),
        ),
    ]
