# Generated by Django 4.0 on 2021-12-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_order_shipping_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_type',
            field=models.IntegerField(choices=[(1, 'Pickup in person'), (2, 'Home shipping')], default='1'),
        ),
    ]
