# Generated by Django 4.0 on 2021-12-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_order_shipping_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Credit card'), (3, 'Bank transfer')], null=True),
        ),
    ]
