# Generated by Django 4.0 on 2021-12-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_order_address_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Order information received'), (2, 'Order packaging in progress'), (3, 'Order sent to customer'), (4, 'Order finished')], null=True),
        ),
    ]
