# Generated by Django 4.0 on 2021-12-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_payed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Information about the order received'), (2, 'Order packaging in progress'), (3, 'Order sent to customer'), (4, 'Order finished')], default=1, null=True),
        ),
    ]
