# Generated by Django 4.0.1 on 2022-02-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_discountcodeusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='user',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='email',
            field=models.TextField(null=True),
        ),
    ]
