# Generated by Django 4.0.1 on 2022-02-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_newsletter_user_newsletter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_paid',
            field=models.FloatField(null=True),
        ),
    ]
