# Generated by Django 4.0 on 2021-12-08 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('rating', models.TextField(choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')])),
                ('is_bestseller', models.BooleanField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('subcategory_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subcategory')),
            ],
        ),
    ]
