# Generated by Django 4.0 on 2021-12-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_subcategory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.TextField(choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')]),
        ),
    ]
