# Generated by Django 4.0 on 2021-12-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='producent_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
